### ISSUE TITLE
Engine not running

### ISSUE THREAD

**Issue by Dr-42** [NyxTheShield/Godot-Smash-Engine#1]
I imported the project today on the latest Godot. It shows a lot of bugs, can you fix it?
I came by this on reddit and really want to develop a fighting game

**Comment by ikoas** [comment]
For what I can gather, one of the issues has to do with the Sound.gd file not using the enum implementation of Godot 3.1.
It seems to be a quick fix. I'm not sure If other scripts on the project suffer some of the consequences of the updates to Godot, but If I'm able to get this running on the latest version of Godot I'll let you know, but the author of the project doesn't seem to be updating or maintaining this repository anymore so I'll be checking forks of this project or even forking it myself.

**Comment by ikoas** [comment]
The quick and easy way to get this project running is downloading a previous version to Godot 3.1 .
For what I found the versions that work are 3.0 to 3.0.6 here is link to download whatever version you like best [https://downloads.tuxfamily.org/godotengine/](url)

As for me trying to make this project compatible for the current version of Godot, I won't, for what I've seen of the project I don't think I would be able to work it into I state I would be satisfied without having to basically redo the whole thing.
